before_script:
  - psql -c 'create database teenyurl;' -U postgres
language: node_js
script: "./build_ci.sh"
services:
  - redis-server
env:
  - VCAP_SERVICES='{"postgres": [{"name" : "teenyurl-postgres", "credentials" : { "database" : "teenyurl", "username" : "postgres" }}]}'
